#!/usr/bin/env python3

import argparse
import string
import base64
import hmac
import hashlib
import time
import sys

parser = argparse.ArgumentParser(prog="./ft_otp.py", description="./ft_otp.py generates One-Time-Passwords based on a provided 64 characters hexadecimal key", epilog="Made by @P0ulp1")
parser.add_argument('-g', nargs=1, metavar="file.hex", required=False, help="A .hex file that contains a 64 characters hexadecimal password")
parser.add_argument('-k', nargs=1, metavar="file.key", required=False, help="Generates a Ont-Time-Password using the .key file containing the key generated by ./ft_otp.py -g")
args = vars(parser.parse_args())

def err(code, msg):
	print(msg)
	exit(code)

def parsing_bis():
	if (args['g'] == None and args['k'] == None):
		err(1, "./ft_otp.py: error: You must use the -g or -k option")
	elif (args['g'] and args['k']):
		err(2, "./ft_otp.py: error: You must use either -g or -k but not both")
	
	# if (args['k'][0].endswith(".key") == False):
	# 	err(5, "./ft_otp.key: error: The extension of the key file is invalid")


def generate_key():
	try:
		if (args['g'][0].endswith(".hex") == False):
			err(4, "./ft_otp.py: error: The extension of the hex file is invalid")

		with open(args['g'][0], 'r') as file:
			data = file.read()
			for char in data:
				if (char not in string.hexdigits and char != '\n'):
					err(3, "./ft_otp.py: error: The provided .hex file is invalid")

			with open('otp.key', 'x') as keyfile:
				datab32 = base64.b32encode(data.encode())
				keyfile.write(str(datab32))

	except FileExistsError as e:
		print("[-] otp.key is already generated. Delete it and run the program again to generate a new one")
	except BaseException as e:
		print("An unexpected error occured: ", e)
	
def idkyet():
	try:
		with open('otp.key', 'r') as file:

			counter = int(time.time() / 30)
			counter_bytes = counter.to_bytes(8, sys.byteorder)
			key = file.read()
			print(key)
			decoded_key = base64.b32decode(key.encode())
			print(decoded_key)
			hashed = hmac.new(counter_bytes, None, 'sha1')
			print(hashed.digest())

	except BaseException as e:
		print("An unexpected error occured: ", e)

if (__name__ == "__main__"):
	parsing_bis()
	generate_key()
	idkyet()